sudo: true
language: node_js
node_js:
  - "7.0"

cache:
  directories:
    - node_modules
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@5; fi
install:
  - npm install
script:
  - npm run test